# Basic options
title: Advanced Regression Analysis with R
short_name: advanced-regression
developers: Eilis Hannon
description: This course builds on the Beginner’s Regression workshop where you will learn how to use regression models with R to model complex, multi-dimensional datasets and make more nuanced comparisons. 
n_sessions: 1
prereq: Introduction to R, Introduction to Regression with R
url: https://coding-for-reproducible-research.github.io/advanced-regression-with-r

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
    sort_by: lesson

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Build settings
theme: jekyll-theme-slate
